import type { Reporter, ReviewReport, Finding } from '../types.js';

export class MarkdownReporter implements Reporter {
  async render(_report: ReviewReport): Promise<void> {
    // No-op: markdown is generated on demand via buildPRSummaryComment/buildInlineComment.
    // Actual posting is done by GitHubOps.
  }
}

export function buildPRSummaryComment(report: ReviewReport): string {
  const { summary } = report;
  const { traditional, vcr } = summary.traditionalComparison;

  const severityTable = ['critical', 'high', 'medium', 'low']
    .filter((s) => (summary.bySeverity[s] ?? 0) > 0)
    .map((s) => `| ${s} | 0 | ${summary.bySeverity[s]} |`)
    .join('\n');

  return `## 🔍 VCR Review — Side by Side

| Metric | Traditional Review | VCR Review |
|--------|-------------------|------------|
| CI Status | ✅ All green | ✅ But circular tests detected |
| Coverage | 94% | ~31% effective (after TORS) |
| Findings | ${traditional.findings} | ${vcr.findings} |
${severityTable}
| Wait time | ${traditional.waitTime} | ${vcr.time} |
| Human cost | ${traditional.cost} | $0 (review only) |
| AI cost | $0 | ${vcr.cost} |
| Risk | ${traditional.riskMissed} | ${vcr.riskCaught} |

### Findings by Layer

${report.layers
  .filter((l) => l.findings.length > 0)
  .map((l) => {
    const layerFindings = l.findings
      .map((f) => {
        const sev = f.severity === 'critical' ? '🔴' : f.severity === 'high' ? '🟠' : f.severity === 'medium' ? '🟡' : '⚪';
        return `- ${sev} **${f.id}** ${f.title} (\`${f.file}${f.line ? ':' + f.line : ''}\`)`;
      })
      .join('\n');
    return `**Layer ${l.layer} — ${l.name}**\n${layerFindings}`;
  })
  .join('\n\n')}

---
*Generated by [VCR Demo](https://virtuslab.github.io/visdom-code-review/) in ${report.summary.totalDurationMs < 60000 ? Math.round(report.summary.totalDurationMs / 1000) + 's' : Math.round(report.summary.totalDurationMs / 60000) + 'min'}*
`;
}

export function buildInlineComment(finding: Finding): string {
  const sevIcon = finding.severity === 'critical' ? '🔴'
    : finding.severity === 'high' ? '🟠'
    : finding.severity === 'medium' ? '🟡'
    : '⚪';

  let comment = `${sevIcon} **${finding.id} [${finding.severity.toUpperCase()}]** ${finding.title}\n\n`;
  comment += `${finding.description}\n`;
  if (finding.suggestion) {
    comment += `\n**Suggestion:** ${finding.suggestion}\n`;
  }
  if (finding.lens) {
    comment += `\n*Lens: ${finding.lens} | Confidence: ${(finding.confidence * 100).toFixed(0)}%*`;
  }
  return comment;
}
